# Generated by Django 2.1.1 on 2019-04-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodename', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('bytes_in_value', models.CharField(max_length=100)),
                ('bytes_out_value', models.CharField(max_length=100)),
                ('cpu_idle_value', models.CharField(max_length=100)),
                ('disk_free_value', models.CharField(max_length=100)),
                ('load_fifteen_value', models.CharField(max_length=100)),
                ('load_five_value', models.CharField(max_length=100)),
                ('load_one_value', models.CharField(max_length=100)),
                ('mem_buffers_value', models.CharField(max_length=100)),
                ('mem_cached_value', models.CharField(max_length=100)),
                ('mem_free_value', models.CharField(max_length=100)),
                ('pkts_in_value', models.CharField(max_length=100)),
                ('pkts_out_value', models.CharField(max_length=100)),
                ('proc_run_value', models.CharField(max_length=100)),
                ('proc_total_value', models.CharField(max_length=100)),
                ('swap_free_value', models.CharField(max_length=100)),
                ('metrics', models.CharField(max_length=100)),
                ('value', models.FloatField(blank=True)),
                ('label', models.IntegerField(choices=[(1, '正常'), (-1, '异常'), (0, '未标记')], default=0)),
            ],
            options={
                'ordering': ['nodename', 'timestamp'],
                'db_table': 'sampledb',
            },
        ),
        migrations.AlterUniqueTogether(
            name='prisample',
            unique_together={('nodename', 'timestamp')},
        ),
    ]
