# Generated by Django 2.1.1 on 2019-05-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampleManage', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Metric',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('metric', models.CharField(max_length=30)),
        #     ],
        #     options={
        #         'db_table': 'metric',
        #     },
        # ),
        migrations.CreateModel(
            name='Nodename',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodename', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'nodename',
            },
        ),
    ]
