# Generated by Django 2.1.1 on 2019-05-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampleManage', '0002_metric_nodename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'metric',
            },
        ),
        migrations.AlterField(
            model_name='nodename',
            name='nodename',
            field=models.CharField(max_length=60),
        ),
    ]
