# Generated by Django 2.1.1 on 2019-05-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampleManage', '0003_auto_20190505_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisample',
            name='bytes_in_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='prisample',
            name='bytes_out_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='prisample',
            name='cpu_idle_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='prisample',
            name='disk_free_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='prisample',
            name='load_fifteen_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='prisample',
            name='load_five_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='prisample',
            name='load_one_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='prisample',
            name='mem_buffers_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='prisample',
            name='mem_cached_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='prisample',
            name='mem_free_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='prisample',
            name='pkts_in_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='prisample',
            name='pkts_out_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='prisample',
            name='proc_run_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='prisample',
            name='proc_total_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='prisample',
            name='swap_free_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
