# Generated by Django 2.1.1 on 2019-05-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampleManage', '0004_auto_20190505_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'metric',
            },
        ),
    ]
