# Generated by Django 2.1.1 on 2019-05-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampleManage', '0004_auto_20190524_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodename', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(max_length=100)),
                ('bytes_in_value', models.FloatField(blank=True, max_length=20, null=True)),
                ('bytes_out_value', models.FloatField(blank=True, max_length=20, null=True)),
                ('cpu_idle_value', models.FloatField(blank=True, max_length=20, null=True)),
                ('disk_free_value', models.FloatField(blank=True, max_length=20, null=True)),
                ('load_fifteen_value', models.FloatField(blank=True, max_length=20, null=True)),
                ('load_five_value', models.FloatField(blank=True, max_length=20, null=True)),
                ('load_one_value', models.FloatField(blank=True, max_length=20, null=True)),
                ('mem_buffers_value', models.FloatField(blank=True, max_length=20, null=True)),
                ('mem_cached_value', models.FloatField(blank=True, max_length=20, null=True)),
                ('mem_free_value', models.FloatField(blank=True, max_length=20, null=True)),
                ('pkts_in_value', models.FloatField(blank=True, max_length=20, null=True)),
                ('pkts_out_value', models.FloatField(blank=True, max_length=20, null=True)),
                ('proc_run_value', models.FloatField(blank=True, max_length=20, null=True)),
                ('proc_total_value', models.FloatField(blank=True, max_length=20, null=True)),
                ('swap_free_value', models.FloatField(blank=True, max_length=20, null=True)),
                ('label', models.IntegerField(choices=[(1, '正常'), (-1, '异常'), (0, '未标记')], default=0)),
            ],
            options={
                'ordering': ['nodename', 'timestamp'],
                'db_table': 'prosampledb',
            },
        ),
        migrations.AlterUniqueTogether(
            name='prosample',
            unique_together={('nodename', 'timestamp')},
        ),
    ]
