# Generated by Django 2.1.1 on 2019-06-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampleManage', '0005_auto_20190528_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('algorithmid', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('algorithmname', models.CharField(max_length=50)),
                ('algorithmtype', models.IntegerField(choices=[(0, '预测'), (1, '检测')], default=0)),
                ('istrain', models.IntegerField(choices=[(0, '无需训练模型'), (1, '需训练模型')], default=0)),
                ('algorithmparameter', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'algorithm',
            },
        ),
    ]
