# Generated by Django 2.1.1 on 2019-05-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampleManage', '0006_auto_20190505_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisample',
            name='timestamp',
            field=models.DateTimeField(max_length=100),
        ),
    ]
