# Generated by Django 2.1.1 on 2019-06-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampleManage', '0006_algorithm'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methodname', models.CharField(max_length=50)),
                ('algorithm', models.CharField(max_length=50)),
                ('paramvalue', models.CharField(max_length=300)),
                ('path', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'predictmethod',
            },
        ),
    ]
