# Generated by Django 2.1.1 on 2019-06-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampleManage', '0007_predictmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='algorithmid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
