# Generated by Django 2.1.1 on 2019-06-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampleManage', '0008_auto_20190609_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mulvisualize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedimensionname', models.CharField(max_length=50)),
                ('dedimensionalgorithm', models.CharField(max_length=50)),
                ('dedimensionnodelist', models.CharField(max_length=1000)),
                ('dedimensionmetrics', models.CharField(max_length=1000)),
                ('dedimensionalparamvalue', models.CharField(max_length=300)),
                ('dedimensionpath', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dedimension',
            },
        ),
    ]
